# Generated by Django 3.1.5 on 2021-01-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discountPrice', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
    ]
