# Generated by Django 3.1.5 on 2021-01-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(default='2', max_length=200),
            preserve_default=False,
        ),
    ]
